default:
  @just --list

bios:
  systemctl reboot --firmware-setup

changelogs:
  rpm-ostree db diff --changelogs

distrobox-boxkit:
  echo 'Creating Boxkit distrobox ...'
  distrobox create --image ghcr.io/ublue-os/boxkit -n boxkit -Y

distrobox-debian:
  echo 'Creating Debian distrobox ...'
  distrobox create --image quay.io/toolbx-images/debian-toolbox:unstable -n debian -Y

distrobox-opensuse:
  echo 'Creating openSUSE distrobox ...'
  distrobox create --image quay.io/toolbx-images/opensuse-toolbox:tumbleweed -n opensuse -Y
 
distrobox-ubuntu:
  echo 'Creating Ubuntu distrobox ...'
  distrobox create --image quay.io/toolbx-images/ubuntu-toolbox:22.04 -n ubuntu -Y
  
setup-flatpaks:
  echo 'Setting up your flatpaks...'
  flatpak install -y --user \\
  com.discordapp.Discord \\
  com.todoist.Todoist \\
  com.visualstudio.code \\
  org.gnome.World.Secrets \\
  com.valvesoftware.Steam \\
  com.valvesoftware.Steam.CompatibilityTool.Proton-Exp \\
  com.spotify.Client
  
setup-firefox:
  echo 'Setting up Firefox...'
  echo 'Opening firefox to generate config, please close this window.'
  flatpak run org.mozilla.firefox
  git clone https://github.com/rafaelmardojai/firefox-gnome-theme
  ./firefox-gnome-theme/scripts/install.sh -f ~/.var/app/org.mozilla.firefox/.mozilla/firefox
  rm -rf ./firefox-gnome-theme
 
update:
  rpm-ostree update
  flatpak update -y
  distrobox upgrade -a
